### ISSUE TITLE
v1.5 has a problem with the "Extra Mod Diamond" added to the toolbar when used in combination with stackoverflow-code-expando

### ISSUE THREAD

**Issue by DavidPostill** [shu8/SE_OptionalFeatures#8]
v1.5 has a problem with the "Extra Mod Diamond" added to the toolbar when used in combination with stackoverflow-code-expando

When stackoverflow-code-expando is disabled there is no issue.

Appears to be a z-ordering issue?

Firefox 39, Windows 7 4Bit. 

![screenshot - 16_07_2015 19_12_24](https://cloud.githubusercontent.com/assets/7079224/8731379/fb155ae8-2bee-11e5-8d12-7469069692a6.png)

**Comment by shu8** [comment]
@DavidPostill it shouldn't happen anymore! I changed the z-index to 1001!: https://github.com/shu8/SE_OptionalFeatures/blob/master/features.user.js#L884. And [so-code-expando](http://userscripts-mirror.org/scripts/review/111973) has a z-index of 1000.... so it should be fixed - could you double check again please??

**Comment by DavidPostill** [comment]
The image above was a snapshot after installing 1.5.1. It's difficult to test on demand as it only happens when there is a blue diamond (ie updates to meta). When I disable expando I can't retest as the diamond is white and it works.

**Comment by DavidPostill** [comment]
This is definately **after** installing 1.5.1.

### Expando enabled

![screenshot - 16_07_2015 21_26_38](https://cloud.githubusercontent.com/assets/7079224/8734405/be92e956-2c01-11e5-8ea1-b3d184b5a730.png)

Popdown is behind  the first code block (which has been expanded).

### Expando disabled

![screenshot - 16_07_2015 21_27_10](https://cloud.githubusercontent.com/assets/7079224/8734398/b58f5876-2c01-11e5-9d86-80d1e7f6832b.png)

As you can see in the second image it is better (with expando disabled) as it is not behind the first code block, but there is still a problem with the bottom part of the popdown (the white backgound doesn't continue all the way to the bottom.

**Comment by shu8** [comment]
@DavidPostill I'll look into it! Probably will be fixed by tomorrow :) Could you please give me the link to that question so I have something to test it on? Thanks!

And I'm aware of the white block not going to the end - I might try fixing that as well :P

**Comment by DavidPostill** [comment]
The question is this one. 

http://stackoverflow.com/questions/31463877/how-do-i-use-multiple-cxf-endpoints-to-call-a-webservice-in-camel

By the way there is no hurry to fix it, it is not
a showstopper ... I'm just happy that the optional features are working for me again.
I've no idea why they stopped working (disappeared) and magically started
working again, unless it was something to do with the Firefox upgrade from
38 to 39 ...

## 

David Postill

**Comment by shu8** [comment]
@DavidPostill yeah I know - no hurry, but I'll do it whenever I can :)

The script _might_ have started working again because of V1.5 - I changed one of the scripts that were required - it worked for somebody else, so it probably worked for you!

Thanks for the link :)

**Comment by DavidPostill** [comment]
Note the expanded code block goes on top of the top bar as well as the pop down.
![screenshot - 16_07_2015 21_57_44](https://cloud.githubusercontent.com/assets/7079224/8735091/242dc872-2c06-11e5-910c-47a524e39c1e.png)

**Comment by shu8** [comment]
@DavidPostill there's nothing my script can do about that - that's just the fault of the **_extremely**_ high z-index set by your other script! :P

**Comment by DavidPostill** [comment]
Hmm. I changed the z-index in the other script to 1 - it didn't make any difference.

**Comment by shu8** [comment]
@DavidPostill  It seems I'll have to tweak some CSS in your expanding script to make this work - I'll check properly when I sit down and look at it properly :)

**Comment by shu8** [comment]
I cannot reproduce this:

![](https://cloud.githubusercontent.com/assets/8850830/8745414/8d396058-2c77-11e5-8eaa-40442dc536fb.png)

(code block has been 'expanded') 

I assume this has been fixed as a side effect of my fix for #9 - @DavidPostill please can you update to 1.6 DEV and see if this issue has been fixed?

**Comment by DavidPostill** [comment]
Still happens for me :(

![screenshot - 17_07_2015 14_18_23](https://cloud.githubusercontent.com/assets/7079224/8746113/27cfcc00-2c7e-11e5-9a63-852bba2e3e20.png)

![screenshot - 17_07_2015 14_20_49](https://cloud.githubusercontent.com/assets/7079224/8746140/55c91508-2c7e-11e5-9ccc-8d57d75c2b16.png)

Code block not expanded:

![screenshot - 17_07_2015 14_21_33](https://cloud.githubusercontent.com/assets/7079224/8746149/6a994818-2c7e-11e5-9468-203755b2f92b.png)

**Comment by shu8** [comment]
@DavidPostill Weird... I'll check again, but I'm done for today :P maybe tomorrow ;)

**Comment by shu8** [comment]
@DavidPostill You didn't say you had fixed topbar enabled!

Anyway this is all fixed if you remove the `.css("z-index", 1000)` on line 19 (in the `expando` function) of stackoverflow-code-expando, making it look like this:

```
function expando() {
    var maxHeight = null;
    $("pre").click(function() {
```

![this](https://cloud.githubusercontent.com/assets/8850830/8761025/587f5ca2-2d33-11e5-9cf8-3ab90bc63a8d.png)

Also, please update to the new DEV version - I just pushed a version out the removes the unnecessary 'fix' I  added last time for this that didn't even work!

Thanks! :)

**Comment by DavidPostill** [comment]
Ah. Next time I will ask you how to dump a list of all my enabled options  to include in the bug report ;). Working perfectly with the expando tweak and the latest dev dersion. Well done, and thanks for all the hard work! You can close this bug.

**Comment by DavidPostill** [comment]
Confirmed as fixed

**Comment by shu8** [comment]
@DavidPostill welcome :) and PS - if you want a dump, just set the options from `add features`, click `save`, and open the console - there will be a dump there ;)

**Comment by DavidPostill** [comment]
Cool. I'll remember that for next time ;)

## 

David Postill
